### ISSUE TITLE
[Trouver Parchment alert] Add config group to onConfigChanged

### ISSUE THREAD

**Issue by YvesW** [zlight97/runelite-plugins#1]
Currently your ConfigChanged event is firing for every config changed in any plugin. Please use https://static.runelite.net/api/runelite-client/net/runelite/client/events/ConfigChanged.html#getGroup()

Additionally, it'd be nice to disable the warning if the non-parched item is protected, and to add a couple tags to the plugin such as "lock" so people can actually find the plugin when searching for the overlay text.

**Comment by zlight97** [comment]
Closing issue. Update has been made, waiting on runelite approval.
Thanks for the comment 👍
