### ISSUE TITLE
Customizability issue

### ISSUE THREAD

**Issue by loggz1996** [zlight97/runelite-plugins#2]
Could you make it possible to add/remove the default selected items, a lot of people disable this plugin due to it warning for items they don't care if they lose such as the standard ava's etc then end up losing the items they do care for, as they forget to turn it back on. 

Would be a perfect plugin if it wasn't for this slight issue.

Cheers

**Comment by zlight97** [comment]
Hey, I've implemented this, and requested the change to runelite. Expect it to come out in a few days time. You will be able to remove items through item name or id in a comma seperated list. Please see the readme if you want more info.
Thanks for the suggestion 👍
